# Set the theme to "TwoDark"
# --theme="Catppuccin-mocha"

# Show line numbers, Git modifications and file header (but no grid)
--style="header,numbers,changes"

# Use italic text on the terminal (not supported on all terminals)
--italic-text=always

# Use C++ syntax for Arduino .ino files
--map-syntax "*.ino:C++"

# Use moor for pager
--pager "moor  -no-linenumbers"
