cacheDir: C:\Users\simsr\.local\share\scoop\apps\pnpm\current\cache
stateDir: C:\Users\simsr\.local\share\scoop\apps\pnpm\current\state
storeDir: C:\Users\simsr\.local\share\scoop\apps\pnpm\current\store
