unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -as terminal-features ",xterm-256color:RGB:mouse:title:strikethrough:overline:usstyle"

set -g mouse-selection on
set -s set-clipboard external
# for neovim
set -g paste-detection off


set -g allow-predictions on

set -g @plugin 'psmux-plugins/ppm'

set -g @plugin 'psmux-plugins/psmux-sensible'
set -g @plugin 'psmux-plugins/psmux-pain-control'
set -g @plugin 'psmux-plugins/psmux-resurrect'
set -g @plugin 'psmux-plugins/psmux-continuum'

set -g status on
set -g status-position bottom
set -g status-interval 5
set -g status-justify left

set -g display-panes-time 3000
set -g display-time 3000

set -g @catppuccin-flavor 'mocha'
set -g @catppuccin-show-powerline 'on'
set -g @catppuccin-window-style 'rounded'

set -g @plugin 'psmux-plugins/psmux-cpu'
set -g @plugin 'psmux-plugins/psmux-prefix-highlight'
set -g @plugin 'psmux-plugins/psmux-theme-catppuccin'

# Plugin manager (must be last line)
run '~/.psmux/plugins/ppm/ppm.ps1'
